"""Added indexes in the expense table

Revision ID: 4bd522145653
Revises: f5f4489683ea
Create Date: 2024-12-14 11:22:23.359319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4bd522145653"
down_revision = "f5f4489683ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expense_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_expense_typeOfExpense"), ["typeOfExpense"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_typeOfExpense"))
        batch_op.drop_index(batch_op.f("ix_expense_date"))

    # ### end Alembic commands ###
