"""Added date column to the expense table

Revision ID: f5f4489683ea
Revises: e144f83f1b45
Create Date: 2024-12-14 10:59:01.756950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5f4489683ea"
down_revision = "e144f83f1b45"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE expense SET date = CURRENT_DATE WHERE date IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.DATE(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.alter_column("date", existing_type=sa.DATE(), nullable=True)

    # ### end Alembic commands ###
